config/routes.rb
Rails.application.routes.draw do

  
  
  root "movies#index"

  resources:movies do
    resources :reviews
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base

	validates :title, :released_on, :duration, presence: true

	validates :description, length: {minimum: 25}

	validates :total_gross, numericality: {greater_than_or_equal_to: 0}

	RATINGS = %w(G PG PG-13 R NC-17)

	validates :rating, inclusion: {in: RATINGS}

	has_many :reviews, dependent: :destroy


	has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:style/placeholder.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	def flop?
		total_gross.blank? || total_gross < 50000000
	end

	def unrated?
		rating.blank?		
	end

	def self.released
		where("released_on <= ?",Time.now).order("released_on desc")
	end

	def self.hit
		where("total_gross >= 3000000000").order("total_gross desc")
	end

	def self.flop
		where("total_gross <= 50000000").order("total_gross")
	end

	def self.recently
		order('created_at').limit(5)
	end

	def validate_title(movie)
		movie.errors[:title]
	end

	def average_stars
	  reviews.average(:stars)
	end

end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :name, presence: true

  validates :comment, length: { minimum: 4 }

  STARS = [1, 2, 3, 4, 5]

	validates :stars, inclusion: { 
	  in: STARS,
	  message: "must be between 1 and 5"
	}
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@event = ["BugSmah","Hackaton","BaseCamp"]
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  	@movie = Movie.recently
  end

  def show
  	@movie = Movie.find(params[:id])
  end

  def edit
  	@movie = Movie.find(params[:id])
  end

  def update
  	# The fail method in Ruby intentionally raises an exception.
  	# fail
  	@movie = Movie.find(params[:id])
  	# movie_params = params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross)
  	if @movie.update(movie_params)
  	# render "show" 
  	  redirect_to movie_path, notice: "Movie was updated successfully"
    else
      render :edit
    end
  	# we can use the "redirect_to @movie" it mean that you go to show method in MoviesController
  end

  def new
  	@movie = Movie.new
  end

  def create
    # movie_params = params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross)
	  @movie = Movie.new(movie_params)
	  if @movie.save
	    redirect_to @movie, notice: "Movie was created successfully"
    else
      render :new
    end
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to root_path, alert: "Movie successfully deleted!"
	end

	private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :set_movie
	def index
		@reviews = @movie.reviews
	end

	def new
		@reviews = @movie.reviews.new
	end

	def create
		@reviews = @movie.reviews.new(reviews_params)
		if @reviews.save
			redirect_to movie_reviews_path, notice: "Thank for review #{@movie.title}!"
		else
			render :new
		end
	end

	private

	def reviews_params
		params.require(:review).permit(:name, :stars, :comment)
	end

	def set_movie
		@movie = Movie.find(params[:movie_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	def format_total_gross(movie)
		if movie.flop?
		  content_tag(:strong, 'Flop!')
		     # this also works: "<strong>Free</strong>".html_safe
		else
		  number_to_human(movie.total_gross)
		end
	end

	def format_unrated(movie)
		if movie.unrated?
			content_tag(:strong, 'Unrating!')
		else
			movie.rating
		end
	end

	def image_for(movie)
		if movie.image_file_name.blank?
			image_tag('placeholder.jpg', class: "img-rounded")
		else
			image_tag(movie.image.url(:thumb))
		end
	end

	def format_average_stars(movie)
		if movie.average_stars.nil?
		  content_tag(:strong, 'No reviews')
		else
		  pluralize(number_with_precision(movie.average_stars, precision: 1) , 'star')

  end
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/events/index.html.erb
<h1><%= @event.size %> Event</h1>
<ul>
	<% @event.each do |var| %>
		<li><%= var %></li>
	<% end %>
</ul>

app/views/layouts/_footer.html.erb
<footer class="footer-distributed">

			<div class="footer-right">

				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-linkedin"></i></a>
				<a href="#"><i class="fa fa-github"></i></a>

			</div>

			<div class="footer-left">

				<p class="footer-links">
					<a href="#">Home</a>
					·
					<a href="#">Blog</a>
				</p>

				<p>Mann Makara &copy; 2016</p>
			</div>

		</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top" role="banner">
  <div class="container">
  	<div class="navbar-header">
  		<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
  			<span class="sr-only">Toggle Navigation</span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  		</button>
  		<a class="navbar-brand" href=<%= root_path %> >Super-Heroic Flix</a>
  	</div>
  	<nav class="collapse navbar-collapse" role="navigation">
  		<ul class="nav navbar-nav">
  			<li><%= link_to 'All Movies', movies_path %></li>
  			<li><%= link_to 'Add New Movie', new_movie_path %></li>
  		</ul>
  	</nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside style="float: right; background: #F0F0F0; width: 200px;">
  <nav>
    <ul>
      <li>
        <%= link_to 'All Movies', movies_path %>
      </li>
      <li>
        <%= link_to 'Add New Movie', new_movie_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Super-Heroic Flix</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<% if flash[:notice] %>
	<div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>


<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/movies/_footer.html.erb
<footer>
  <p>
    Copyright &copy; 2016
    <%= link_to 'The Pragmatic Studio','http://pragmaticstudio.com' %>
  </p>
</footer>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= render 'shared/errors', object: @movie %>
  <fieldset>
    <p class="required">
      <%= f.label :title %><br/>
      <%= f.text_field :title, autofocus: true, :class => 'form-control' %>
    </p>
    <p class="required">
      <%= f.label :description %><br/>
      <%= f.text_area :description, cols: 40, rows: 7 , :class => 'form-control' %>
    </p>
    <p class="required">
      <%= f.label :rating %><br/>
      <%= f.select :rating, Movie::RATINGS, prompt: "Pick one", :class => 'form-control' %>
    </p>
    <p class="required">
      <%= f.label :released_on %><br/>
      <%= f.date_select :released_on, :class => 'form-control' %>
      <!-- We can also use date_field -->
    </p>
    <p class="required">
      <%= f.label :cast %><br/>
      <%= f.text_area :cast, cols: 40, rows: 7, :class => 'form-control' %>
      <!-- We can also use date_field -->
    </p>
    <p class="required">
      <%= f.label :director %><br/>
      <%= f.text_field :director , :class => 'form-control' %>
      <!-- We can also use date_field -->
    </p>
    <p class="required">
      <%= f.label :duration %><br/>
      <%= f.text_field :duration , :class => 'form-control' %>
      <!-- We can also use date_field -->
    </p>
    <p class="required">
      <%= f.label :total_gross %><br/>
      <%= f.number_field :total_gross , :class => 'form-control' %>
    </p>
    <p class="required">
      <%= f.label :image %><br/>
      <%= f.file_field :image , :class => 'form-control' %>
      <!-- We can also use date_field -->
    </p>
    <p>
      <%= f.submit :class => 'btn btn-primary'%> 
      <%= link_to "Cancel", movies_path, :class => "btn btn-danger" %>
    </p>
  </fieldset>
<% end %>

app/views/movies/edit.html.erb
<div class="container">
	<h3>Edit <%= @movie.title %></h3>
	<%= render 'form' %>
</div>

app/views/movies/index.html.erb
<div class="container">
	<div class="row">
		<% @movie.each do |var| %>
			<div class="col-md-4">
				<%= image_for(var) %>
				<h3><%= link_to(var.title, var) %></h3>
				<p>Description : <%= truncate(var.description,length: 40,seperator:' ') %></p>
				<p>Rating: (<%= format_unrated(var) %>)</p>
				<p>Total Gross: <%=format_total_gross(var) %></p>
				<p>Release Date :<%= var.released_on %> (<%= time_ago_in_words(var.released_on) %>)</p>
			</div>
		<% end %>
	</div>

</div>

app/views/movies/new.html.erb
<div class="container">
	<h3>Create the new Movie</h3>
	<%= render 'form' %>
</div>

app/views/movies/show.html.erb
<li>
	<%= image_for(@movie) %>
	<h1><%= @movie.title %></h1> 
	<p>Description : <%= truncate(@movie.description,length: 40,seperator:' ') %></p>
	<p>Rating: (<%= format_unrated(@movie) %>)</p>
	<p>Average Review: (<%= format_average_stars(@movie) %>)</p>
	<p>Total Gross: <%=format_total_gross(@movie) %></p>
	<p>Release Date :<%= @movie.released_on %> (<%= time_ago_in_words(@movie.released_on) %>)</p>
</li>
<!-- method: :delete is to overide the verb that request to HTTP -->
<!-- data: {confirm: "meassage"} is respone to open dialog to confirm to user to to the action or not -->
<%= link_to "Make review", new_movie_review_path(@movie), :class => "btn btn-success" %>
<%= link_to "Edit", edit_movie_path, :class => "btn btn-primary" %>  <%= link_to "Delete", movie_path, method: :delete, data: {confirm: "Are you sure you want to delete #{@movie.title} Movie"}, :class => "btn btn-info" %> <%= link_to "Who's rating on this movie?", movie_reviews_path(@movie), :class => "btn btn-primary" %> 

app/views/reviews/_form.html.erb
<%= form_for([@movie,@reviews]) do |f| %>
  <%= render 'shared/errors', object: @reviews %>
  <fieldset>
    <p class="required">
      <%= f.label :name %><br/>
      <%= f.text_field :name, autofocus: true, :class => 'form-control' %>
    </p>
    <p class="required">
      <%= f.label :stars %><br/>
      <%= f.select :stars, Review::STARS, prompt: "Pick one", :class => 'form-control' %>
    </p>
    <p class="required">
      <%= f.label :comment %><br/>
      <%= f.text_area :comment, cols: 40, rows: 7 , :class => 'form-control', placeholder: "What did you think?" %>
    </p>
    <p>
      <%= f.submit 'Post', :class => 'btn btn-primary'%> 
      <%= link_to "Cancel", movie_reviews_path, :class => "btn btn-danger" %>
    </p>
  </fieldset>
<% end %>

app/views/reviews/index.html.erb
<div class="container">
	<div class="page-header">
		<h4>Reviews for <%= link_to(@movie.title, @movie) %></h4>
	</div>
	<% if @reviews.size ==0 %>
		<h3>Don't have any review yet </h3>
	<% else %>
		<ul id="reviews">
	  <% @reviews.each do |review| %>
	    <li>
	      <span class="review"><%= pluralize(review.stars, 'star') %></span>
	      <span class="user">by <%= review.name %></span>
	      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
	      <p>
	        &quot;<%= review.comment %>&quot;
	      </p>
	    </li>
	  <% end %>
	</ul>
	<% end -%>
</div>

app/views/reviews/new.html.erb
<div class="container">
	<h3>Create the new review person</h3>
	<%= render 'form' %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h4>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved. 
    </h4>
    <h5>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h5>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>